spring.profiles.active=local
spring.application.name=resume-analyzer
server.servlet.context-path=/resume
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.file-size-threshold=2MB
spring.servlet.multipart.max-request-size=2MB